name: build

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "🛠 Run the build script"
        shell: pwsh
        run: ./build.ps1
      - name: "🌊 Upload new build to Releases"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Master.ps1"
          token: ${{ secrets.GITHUB_TOKEN }}
#     - name: Upload the combined file into artifacts
#       uses: actions/upload-artifact@v3.0.0
#       with:
#         name: tweakfuncs-compiled
#         path: ./Master.ps1
#
