name: build

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "🛠 Run the build script"
        shell: pwsh
        run: ./build.ps1
      - name: "🌊 Upload new build to Releases"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Master.ps1
#     - name: Upload the combined file into artifacts
#       uses: actions/upload-artifact@v3.0.0
#       with:
#         name: tweakfuncs-compiled
#         path: ./Master.ps1
#
