name: build

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run the build script
        shell: pwsh
        run: ./build.ps1
      - name: Upload the combined file into artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: build
          path: ./Master.ps1

